name: marcelopontes
favicon: null
layout_spectrum: 0.28821
typography_spectrum: 0.7203917847946286
title: marcelo pontes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.20986431348137558
  lightness: 0.7955897187348455
  saturation: 0.9751135685946792
  rhythmicContrast: 0.6645885757170618
purpose: []
